apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-aurora
spec:
  displayName: Aurora
  author:
    name: zhiqixiaozhu
    website: https://www.halosb.com/
  description: 精致、温暖、有呼吸感的个人空间
  logo: https://www.halosb.com/upload/cover-1777443073469.webp
  homepage: https://www.halosb.com/
  settingName: "theme-aurora-setting"
  configMapName: "theme-aurora-configmap"
  version: "5.3.2"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halosb/theme-aurora/blob/main/LICENSE"
  customTemplates:
    page:
      - name: 关于页面
        description: "关于我的个人介绍页面"
        screenshot: ""
        file: page_about
      - name: 项目展示
        description: "展示个人项目与作品"
        screenshot: ""
        file: page_projects
      - name: 友情链接页
        description: "自定义友链展示页面"
        screenshot: ""
        file: page_links
      - name: 留言板
        description: "访客留言、交流与反馈"
        screenshot: ""
        file: page_content
