apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-kukuxin
spec:
  displayName: KukuXin
  author:
    name: KKXLIVE
    website: https://zanecarter.top/
  description: 以代码探索未来，以创造连接世界 ❀
  logo: https://zanecarter.top/upload/IMG_0026.jpeg
  homepage: https://zanecarter.top/
  settingName: "theme-kukuxin-setting"
  configMapName: "theme-kukuxin-configmap"
  version: "5.3.2"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/KKXLIVE/Zane_Digital_Lab/blob/main/LICENSE"
  customTemplates:
    page:
      - name: 关于页面
        description: "关于我的个人介绍页面"
        screenshot: ""
        file: page_about
      - name: 项目展示
        description: "展示个人项目与作品"
        screenshot: ""
        file: page_projects
      - name: 友情链接页
        description: "自定义友链展示页面"
        screenshot: ""
        file: page_links
      - name: 留言板
        description: "访客留言、交流与反馈"
        screenshot: ""
        file: page_content
